export const ACCESS_TOKEN_EXPIRATION_TIME = 60 * 5; // 5 minutes
export const ACCESS_TOKEN_PASSPHRASE = process.env.ACCESS_TOKEN_PASSPHRASE;

export const REFRESH_TOKEN_EXPIRATION_TIME = 60 * 60 * 1; // 1 hour
export const REFRESH_TOKEN_PASSPHRASE = process.env.REFRESH_TOKEN_PASSPHRASE;
